GET http://localhost:8080/api/events HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwicm9sZSI6ImNyZWF0b3IiLCJlbWFpbCI6ImFndXNiYXNhcmkyOTlAZ21haWwuY29tIiwiZXhwIjoxNjUwNzg3MDEyLCJpYXQiOjE2MTkyNTEwMTIsImlzcyI6InhqeCJ9.Pp_8V348oul_D2VHxbNcIzv2Mvdb8UPXpnqP-bwRI3o

{}

###
POST http://localhost:8080/api/events HTTP/1.1
content-type: application/json
Authorization: 

{
    "creator_id": 11,
	"title_event": "Webinar Bla bla bla",
	"link_webinar": "http://wwww.webinar.com",
	"description": "Webinar onlie disaat pandemi",
	"banner": "/files/image/banner",
	"price": 200000,
	"quantity": 150,
	"status": "draft",
	"event_start_date": "2021-05-01T00:00:00-00:00",
	"event_end_date": "2021-05-02T00:00:00-00:00",
	"campaign_start_date": "2021-04-23T00:00:00-00:00",
	"campaign_end_date": "2021-04-29T00:00:00-00:00"
}

###

PUT http://localhost:8080/api/events HTTP/1.1
content-type: application/json
Authorization:  

{
    "id": 2,
    "creator_id": 11,
	"title_event": "Webinar Bla bla bla",
	"link_webinar": "http://wwww.webinar.com",
	"description": "Webinar onlie disaat pandemi",
	"banner": "/files/image/banner",
	"price": 200000,
	"quantity": 150,
	"status": "draft",
	"event_start_date": "2021-05-01T00:00:00-00:00",
	"event_end_date": "2021-05-02T00:00:00-00:00",
	"campaign_start_date": "2021-04-23T00:00:00-00:00",
	"campaign_end_date": "2021-04-29T00:00:00-00:00"
}

###
DELETE http://localhost:8080/api/events HTTP/1.1
content-type: application/json
Authorization:  

{
    "id": 1
}