POST http://127.0.0.1:8080/auth/login HTTP/1.1
content-type: application/json

{
    "username": "superadmin",
    "password": "apasajalah"
}

###

POST http://localhost:8080/auth/register HTTP/1.1
content-type: application/json

{
    "username": "jabrix",
    "fullname": "bang bosqi",
    "email": "agusbasari299@gmail.com",
    "password": "apasajalah",
    "role": "admin"
}


###

GET http://localhost:8080/api/users HTTP/1.1
content-type: application/json

{
    
}

###

POST http://localhost:8080/api/events HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwicm9sZSI6ImNyZWF0b3IiLCJlbWFpbCI6ImFndXNiYXNhcmkyOTlAZ21haWwuY29tIiwiZXhwIjoxNjUwNzg3MDEyLCJpYXQiOjE2MTkyNTEwMTIsImlzcyI6InhqeCJ9.Pp_8V348oul_D2VHxbNcIzv2Mvdb8UPXpnqP-bwRI3o

{
    "creator_id": 11,
	"title_event": "Webinar Bla bla bla",
	"link_webinar": "http://wwww.webinar.com",
	"description": "Webinar onlie disaat pandemi",
	"banner": "/files/image/banner",
	"price": 200000,
	"quantity": 150,
	"status": "draft",
	"event_start_date": "2021-05-01T00:00:00-00:00",
	"event_end_date": "2021-05-02T00:00:00-00:00",
	"campaign_start_date": "2021-04-23T00:00:00-00:00",
	"campaign_end_date": "2021-04-29T00:00:00-00:00"
}

###

POST http://localhost:8080/api/creators HTTP/1.1
content-type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwicm9sZSI6ImFkbWluIiwiZW1haWwiOiJhZ3VzYmFzYXJpMjkwQGdtYWlsLmNvbSIsImV4cCI6MTY1MDc4NjcyMCwiaWF0IjoxNjE5MjUwNzIwLCJpc3MiOiJ4angifQ.vzD9Pijc25_N61TemAgT-JRyGaN43Uvt1pjMCcGZQmc

{
	"username": "kodokijo",
    "fullname": "m hafizh a",
    "email": "agusbasari299@gmail.com",
    "password": "apasajalah",
    "role": "creator"
}


###

GET http://localhost:8080/api/creators HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMiwicm9sZSI6ImFkbWluIiwiZW1haWwiOiJhZ3VzYmFzYXJpMjk5QGdtYWlsLmNvbSIsImV4cCI6MTY1MDc4ODg0MCwiaWF0IjoxNjE5MjUyODQwLCJpc3MiOiJ4angifQ.kh8kOhc-imcALOBebQYSEJbfant_HcL7JJNLyXLD9ow

{

}

###
DELETE http://localhost:8080/api/creators HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMiwicm9sZSI6ImFkbWluIiwiZW1haWwiOiJhZ3VzYmFzYXJpMjk5QGdtYWlsLmNvbSIsImV4cCI6MTY1MDc4ODg0MCwiaWF0IjoxNjE5MjUyODQwLCJpc3MiOiJ4angifQ.kh8kOhc-imcALOBebQYSEJbfant_HcL7JJNLyXLD9ow

{
    "id": 11
}

###

GET http://localhost:8080/seeder HTTP/1.1


###

POST http://localhost:8080/api/detail_report HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6InB3QmtqR2NAbk5RVG9JSS5uZXQiLCJ1c2VybmFtZSI6InZFbklhbEUiLCJleHAiOjE2NTExMjI3MzYsImlhdCI6MTYxOTU4NjczNiwiaXNzIjoieGp4In0.lxCRO8B1bMfbEgP6H57D2jYHdhU3_13uu8PKfiskfqc

{
    "id": 8
}